---
- name: Install XRDP-packages
  apt:
    name: [ 'xrdp' ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes
  when:
    - "'xrdp' in services"
